logout:
    path:   /logout
login:
    pattern:   /login
    defaults:  { _controller: giftletBundle:Security:login }
login_check:
    pattern:   /login_check
giftlet:
    resource: "@giftletBundle/Resources/config/routing.yml"
    prefix:   /

