giftlet\giftletBundle\Entity\Gift:
  type: entity
  table: gifts
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    description:
      type: text
      nullable: true
    link:
      type: string
      length: 500
      nullable: true
    cost:
      type: float
    createddate:
      type: datetime
  manyToOne:
    createdby:
      targetEntity: User
      inversedBy: gifts
      joinColumn:
        name: createdby
        referencedColumnName: id
  oneToMany:
    contributions:
      targetEntity: Contribution
      mappedBy: gift
  lifecycleCallbacks:
    prePersist: [ setCreatedByValue ]
    prePersist: [ setCreatedDateValue ]