parameters:
#    giftlet.example.class: giftlet\giftletBundle\Example

services:
#    giftlet.example:
#        class: %giftlet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
