<?php

namespace Proxies\__CG__\giftlet\giftletBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contribution extends \giftlet\giftletBundle\Entity\Contribution implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setGift($gift)
    {
        $this->__load();
        return parent::setGift($gift);
    }

    public function getGift()
    {
        $this->__load();
        return parent::getGift();
    }

    public function setCreateddate($createddate)
    {
        $this->__load();
        return parent::setCreateddate($createddate);
    }

    public function getCreateddate()
    {
        $this->__load();
        return parent::getCreateddate();
    }

    public function setGifts(\giftlet\giftletBundle\Entity\Gift $gifts = NULL)
    {
        $this->__load();
        return parent::setGifts($gifts);
    }

    public function getGifts()
    {
        $this->__load();
        return parent::getGifts();
    }

    public function setUsers(\giftlet\giftletBundle\Entity\User $users = NULL)
    {
        $this->__load();
        return parent::setUsers($users);
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function setCreatedDateValue()
    {
        $this->__load();
        return parent::setCreatedDateValue();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'amount', 'createddate', 'gift', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}